name: ml_doc_classifier_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas=2.0.3
  - numpy=1.24.3
  - scikit-learn=1.3.0
  - fastapi=0.112.2
  - uvicorn=0.20.0
  - pytest=7.4.4
  - httpx=0.27.0
  - seaborn=0.13.2
  - matplotlib=3.7.2
  - pip=24.2
  - ipykernel=6.29.5