name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download dataset
        run: |
          wget https://archive.ics.uci.edu/ml/machine-learning-databases/00359/NewsAggregatorDataset.zip
          unzip NewsAggregatorDataset.zip -d data

      - name: Run training
        run: ./run/run_model_training.sh

      - name: Run tests
        run: python -m pytest tests/ -vs

      - name: Build Docker image
        run: docker build -t documents_classifier_api .

      - name: Test API
        run: |
          docker run -d -p 80:80 --name documents_classifier_api_container documents_classifier_api
          sleep 10  # Wait for the API to start
          docker ps  # List running containers for debugging
          python classify_headline.py 'computer science'
          docker stop documents_classifier_api_container
          docker rm documents_classifier_api_container